.env
nSystemz/RageMP-C-Tutorial-NemesusTV pull request #3
Opened 2023-07-09 12:18 UTC by mrtuxa

added dotenv for better handling for credentials like discord bot token

2024-02-05 07:19 UTC, TheBlokker requested changes
Paths Updaten siehe in manchen Config Files

2024-02-08 18:45 UTC, mrtuxa commented
> Paths Updaten siehe in manchen Config Files

wo genau??

2024-02-08 19:21 UTC, TheBlokker commented
> ?
In der csproject usw.

2024-03-20 06:12 UTC, DevTimmOfTO commented
Also du müsstest alle commit ohne die paths zuverändern

2024-04-27 16:54 UTC, closed without merging